// <auto-generated />
using System;
using InvesteAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvesteAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240402015853_PrimeiraMigration")]
    partial class PrimeiraMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("InvesteAPI.Models.Investimento", b =>
                {
                    b.Property<int>("investimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("investimentoId"));

                    b.Property<bool>("Resgatado")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("aporteInicial")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("aporteMensal")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("dataFinal")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dataInicial")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("tempoVigencia")
                        .HasColumnType("int");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("valorFinal")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("investimentoId");

                    b.ToTable("Investimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
